### ISSUE TITLE
[Feature request] Ctrl+F to focus search field

### ISSUE THREAD

**Issue by galantra** [ijgnd/anki__add-on_window_search_filter_bar#1]
Ctrl+F is such a common shortcut that I'm always a bit confused when I hit Ctrl+F and the add-on browser doesn't focus on the search field.

**Comment by ijgnd** [comment]
I just uploaded a new version that has the "Ctrl+F" shortcut to ankiweb. Please update. If you run into a problem please let me know.

**Comment by galantra** [comment]
Thank you a lot!
