### ISSUE TITLE
[BUG]  trouble with accessing some config windows when filtering addons

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ijgnd/anki__add-on_window_search_filter_bar#2]
Hi,

I just discovered a very strange bug.

I tried to access the config of "Resize image editor" addon. If I don't filter the addon list I can access the config window with no issue. If I filter the addon list the button stays grey.

I can access the addon "enhance main window" with or without filtering for example.

When filtering for "searchbar", the addon ungreys its own "config" button, even though clicking on it returns "Add-on has no configuration" popup.

I am on anki 2.1.22. I upgraded to 26 but then went back to 22, if that matters.

edit : even stranger. If I filter "r", I can access the config. "re"/"res" and I can't. "resi" and I can

**Comment by ijgnd** [comment]
Thanks for the report. 

The add-on doesn't grey out the config as you reported. I added this as #3. 

Can you access the config if you double click the entry?

My add-on shouldn't completely break your Anki. But for me it's enough that it mostly works so fixing the Config button or enabling a keyboard only workflow if the double click method works is not a high priority for me. I guess a true fix would be to get this merged into Anki.

**Comment by thiswillbeyourgithub** [comment]
I can indeed access via double clicking. I was not aware of this feature.

Could you maybe change the popup to say "Add-on has no configuration popup. If you think it does, try double clicking on the name of the add-on." so that at least in some cases people will know there is such a feature?

I think it's really too bad that people will think some addons have no configuration panel :/

Thank you anyway!

**Comment by ijgnd** [comment]
I just added this to the add-on description:

> Caveat/Limitation: Some users report that sometimes for add-ons that have a config the config button is falsely greyed out when filtering with this add-on. In this case you can still access the add-on config by double clicking the addon name in the list (if you use Anki 2.1.14 or newer).

If you have a better text or if my text can be improved: your feedback is welcome.

**Comment by thiswillbeyourgithub** [comment]
> falsely greyed out **or falsely not-greyed out** when filtering

If I may.

Thank you :)

**Comment by ijgnd** [comment]
done
